In [111]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
pd.set_option('display.mpl_style', 'default') # Make the graphs a bit prettier
plt.rcParams['figure.figsize'] = (15, 5)


usersDF = pd.read_csv('users.csv')
usersDF.head()

   userID state_code party
0       1         AK     D
1       2         AK     D
2       3         AL   NaN
3       4         AL   NaN
4       5         AL   NaN

# Concatenate all of the debate tweets

In [93]:
deb1 = pd.read_csv('tweets_debate1.csv')
deb2 = pd.read_csv('tweets_debate2.csv')
deb3 = pd.read_csv('tweets_debate3.csv')
debvp = pd.read_csv('tweets_debateVP.csv')
frames = [deb1, deb2, deb3, debvp]
df = pd.concat(frames, ignore_index=True)

df.head()

,userID,text,created_at,favorite_count,followers_account,friends_count,location
0,11344,Police start the presidential debate memes swi...,09/26/2016 21:00:00 EDT,1,123,96,"East Point, GA"
1,2061,"RT @thereaIbanksy: become the most positive, e...",09/26/2016 21:00:03 EDT,481,116,244,"Kansas City, MO USA"
2,22644,This is gonna be a stressful ass week.,09/26/2016 21:00:03 EDT,9930,176,163,"Dundee, Oregon"
3,9694,RT @KevinBracken4: #serviceselfie #T2Trun NY M...,09/26/2016 21:00:12 EDT,8135,235,136,NY Metro
4,9087,RT @HillaryClinton: Let's do this. #DebateNigh...,09/26/2016 21:00:13 EDT,141,70,163,"New York, NY"

In [94]:
print('Num of users: ' + str(len(usersDF)))
print('Num of tweets: ' + str(len(df)))

Num of users: 22853
Num of tweets: 60378

In [95]:
#retweets = [item for item in df['text'] if item.startswith('RT') ]
#org_tweets = [item for item in df['text'] if not item.startswith('RT') ]

tweets = df.loc[:,'text']

retweets = [item for item in tweets if item.startswith('RT') ]
org_tweets = [item for item in tweets if not item.startswith('RT') ]

print(str(type(retweets)))

print(str(type(tweets)))

<class 'list'>
<class 'pandas.core.series.Series'>

In [96]:
df.describe()

             userID  favorite_count  followers_account  friends_count
count  60378.000000    60378.000000       60378.000000   60378.000000
mean   11516.136838     7317.397280        2651.535576    1688.215310
std     6724.801878    25786.687507       13697.959984   11074.939779
min        6.000000        0.000000           1.000000       2.000000
25%     5526.000000      312.000000         204.000000     274.000000
50%    11505.000000     1348.000000         444.000000     535.000000
75%    17527.000000     4612.000000        1164.000000    1070.000000
max    22853.000000   310812.000000      197614.000000  172076.000000

In [97]:
df.sort('favorite_count', ascending=False)

,userID,text,created_at,favorite_count,followers_account,friends_count,location
49176,2437,@MsBlazeInc 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮...,10/19/2016 21:59:04 EDT,310812,168995,171540,Nevada
54540,2437,@MsBlazeInc 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮...,10/19/2016 21:59:04 EDT,310812,168995,171540,Nevada
54302,2437,@roeorr 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 🗣...,10/19/2016 21:56:41 EDT,310811,168995,171540,Nevada
48938,2437,@roeorr 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 🗣...,10/19/2016 21:56:41 EDT,310811,168995,171540,Nevada
54413,2437,@uncjay1 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 ...,10/19/2016 21:57:39 EDT,310811,168995,171540,Nevada
49049,2437,@uncjay1 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 ...,10/19/2016 21:57:39 EDT,310811,168995,171540,Nevada
54287,2437,RT @jojokejohn: Very true and Libya and now Ye...,10/19/2016 21:56:31 EDT,310810,168996,171540,Nevada
54067,2437,Very true and Libya and now Yemen and still in...,10/19/2016 21:54:10 EDT,310810,168996,171540,Nevada
53712,2437,@AngelJosiah67 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 ...,10/19/2016 21:50:27 EDT,310810,168996,171540,Nevada
54235,2437,@KeenanHelsabeck 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ ...,10/19/2016 21:55:55 EDT,310810,168996,171540,Nevada
48703,2437,Very true and Libya and now Yemen and still in...,10/19/2016 21:54:10 EDT,310810,168996,171540,Nevada
48348,2437,@AngelJosiah67 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 ...,10/19/2016 21:50:27 EDT,310810,168996,171540,Nevada
48871,2437,@KeenanHelsabeck 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ ...,10/19/2016 21:55:55 EDT,310810,168996,171540,Nevada
48923,2437,RT @jojokejohn: Very true and Libya and now Ye...,10/19/2016 21:56:31 EDT,310810,168996,171540,Nevada
53435,2437,@johnmarki 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 ...,10/19/2016 21:47:00 EDT,310809,168996,171540,Nevada
48045,2437,@TaxiAlejandro 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 ...,10/19/2016 21:46:38 EDT,310809,168996,171540,Nevada
53409,2437,@TaxiAlejandro 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 ...,10/19/2016 21:46:38 EDT,310809,168996,171540,Nevada
48071,2437,@johnmarki 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 ...,10/19/2016 21:47:00 EDT,310809,168996,171540,Nevada
53650,2437,@hitoast 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 ...,10/19/2016 21:49:39 EDT,310809,168996,171540,Nevada
48286,2437,@hitoast 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 ...,10/19/2016 21:49:39 EDT,310809,168996,171540,Nevada
51670,2437,@grameezaliberal 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ ...,10/19/2016 21:27:14 EDT,310808,168996,171519,Nevada
51645,2437,@QRosecorrie607 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭...,10/19/2016 21:26:57 EDT,310808,168996,171519,Nevada
53384,2437,RT @jojokejohn: DISNEY EXCLUSIVE-MICKEY MOUSE-...,10/19/2016 21:46:23 EDT,310808,168996,171540,Nevada
46281,2437,@QRosecorrie607 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭...,10/19/2016 21:26:57 EDT,310808,168996,171519,Nevada
48020,2437,RT @jojokejohn: DISNEY EXCLUSIVE-MICKEY MOUSE-...,10/19/2016 21:46:23 EDT,310808,168996,171540,Nevada
46306,2437,@grameezaliberal 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ ...,10/19/2016 21:27:14 EDT,310808,168996,171519,Nevada
51628,2437,RT @jojokejohn: Where the machine wants you to...,10/19/2016 21:26:48 EDT,310807,168996,171519,Nevada
46264,2437,RT @jojokejohn: Where the machine wants you to...,10/19/2016 21:26:48 EDT,310807,168996,171519,Nevada
46243,2437,@perlop 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 🗣...,10/19/2016 21:26:34 EDT,310807,168996,171519,Nevada
51607,2437,@perlop 🎨 🎨 🎨 🎨 🎨 Шə ρɑɪήʇ ʘϋʀ Шʘʀɭɗ 🍭 🎼 🚮 🕊 🗣...,10/19/2016 21:26:34 EDT,310807,168996,171519,Nevada
...,...,...,...,...,...,...,...
25109,7788,"Wait, I thought the Iran Deal was the worst de...",10/09/2016 22:15:55 EDT,0,353,385,"Milwaukee, WI"
25499,203,She's going to represent the deplorables.,10/09/2016 22:19:13 EDT,0,67,19,Birmingham Alabama
30837,7788,The best part of Hillary's reactions right now...,10/09/2016 21:38:41 EDT,0,353,385,"Milwaukee, WI"
30411,7788,RT @KeithOlbermann: Does Obamacare cover being...,10/09/2016 21:34:42 EDT,0,353,385,"Milwaukee, WI"
30210,7788,RT @edatpost: The camera angles are just incre...,10/09/2016 21:33:08 EDT,0,353,385,"Milwaukee, WI"
1384,7788,SHE'S GOT HIM!!!!!!! #DebateNight,09/26/2016 21:19:35 EDT,0,356,384,"Milwaukee, WI"
29859,7788,Anderson Cooper trying desperately to return t...,10/09/2016 21:30:40 EDT,0,353,385,"Milwaukee, WI"
29736,10658,One on three!! Unfair #debate,10/09/2016 21:29:47 EDT,0,83,126,"Sarasota, FL"
1349,7788,"RT @RuthMarcus: And now, Secretary Clinton bec...",09/26/2016 21:19:18 EDT,0,356,384,"Milwaukee, WI"
29663,14937,Damn! Donald's on the Attack! Hell Yeah!,10/09/2016 21:29:14 EDT,0,8,10,"Demorest, Georgia"
3539,7788,RT @politicalwire: Trump is going to explode,09/26/2016 21:35:46 EDT,0,356,384,"Milwaukee, WI"
3548,7788,RT @anamariecox: HE JUST ADMITTED HE PAYS NO F...,09/26/2016 21:35:51 EDT,0,356,384,"Milwaukee, WI"
28579,7788,You think Bill gives a shit about any of that?...,10/09/2016 21:19:55 EDT,0,353,385,"Milwaukee, WI"
28380,14937,Two Liberal Moderators teaming up with Crooked...,10/09/2016 21:18:13 EDT,0,8,10,"Demorest, Georgia"
28339,7788,The problem Don is that we're going to move in...,10/09/2016 21:17:47 EDT,0,353,385,"Milwaukee, WI"
1290,7788,"RT @rickklein: ""semi-exact.""",09/26/2016 21:18:53 EDT,0,356,384,"Milwaukee, WI"
28236,7788,RT @RonanFarrow: Hillary Clinton really grabbi...,10/09/2016 21:16:41 EDT,0,353,385,"Milwaukee, WI"
28192,7788,"RT @BBCBreaking: ""I have great respect for wom...",10/09/2016 21:16:17 EDT,0,353,385,"Milwaukee, WI"
28036,7788,Kill shot. #Debate,10/09/2016 21:14:58 EDT,0,353,385,"Milwaukee, WI"
1269,7788,RT @BobShrum: @realDonaldTrump Interrupting is...,09/26/2016 21:18:38 EDT,0,356,384,"Milwaukee, WI"
27206,7788,RT @kurteichenwald: I gotta ask: What kind of ...,10/09/2016 21:04:57 EDT,0,353,385,"Milwaukee, WI"
27195,7788,RT @RepUnderwoodSC: Game time. #debatenight,10/09/2016 21:04:45 EDT,0,353,385,"Milwaukee, WI"
27093,7788,RT @DavidLauter: Hillary Clinton's popularity ...,10/09/2016 21:01:47 EDT,0,353,385,"Milwaukee, WI"
27065,7788,Good luck America. We're gonna need it. #Debate,10/09/2016 21:01:08 EDT,0,353,385,"Milwaukee, WI"
26617,7788,I swear I just say a fly on one of the cameras...,10/09/2016 22:29:49 EDT,0,353,385,"Milwaukee, WI"
25929,7788,The people over @realDonaldTrump's shoulders i...,10/09/2016 22:23:09 EDT,0,353,385,"Milwaukee, WI"
1222,7788,"RT @chrislhayes: Dude, it's still on your twit...",09/26/2016 21:18:10 EDT,0,356,384,"Milwaukee, WI"
56315,10658,RT @jimlockwoodshow: Pence asks Kaine “Do you ...,10/04/2016 21:30:20 EDT,0,82,126,"Sarasota, FL"
25523,7788,That was pretty brilliant of Clinton to tie ba...,10/09/2016 22:19:30 EDT,0,353,385,"Milwaukee, WI"
30334,7788,Best #Debate tweet I've seen so far. https://t...,10/09/2016 21:34:00 EDT,0,353,385,"Milwaukee, WI"

In [98]:
# function to get term after hashtag

def getHashtag(tweet):
    tweet = tweet.split()
    hashtags = []
    for item in tweet:
        if item[0] == "#":
            hashtags.append(item)
            
    return hashtags

def getRT(tweet):
    retweets = []    
    if tweet[0:1] == "RT":
        retweets.append(tweet)
    return retweets

def orgtweets(tweet):
    unique_tweets = []
    if tweet[0:1] != "RT":
        unique_tweets.append(tweet)
    return unique_tweets
        
# pd Series
hashtags = df.text.apply(getHashtag)
retweets = [element for element in df['text'].values if element.startswith('RT')]
orgtweets = [element for element in df['text'].values if not element.startswith('RT')]

# print(str(type(hashtags)))
# print(df.loc[2]['text'])
print(hashtags[:10])
print(str(len(orgtweets)))
print(str(len(retweets)))

0                                                 []
1                                                 []
2                                                 []
3                          [#serviceselfie, #T2Trun]
4                                     [#DebateNight]
5                                                 []
6                     [#Lutz, #News, #parkbenchnews]
7                                                 []
8                                          [#Gotham]
9    [#Training., #CSI, #Underwater, #Dive, #Police]
Name: text, dtype: object
29607
30771

In [99]:
ex = "This is my #antiTrump example #tweet"

terms = ex.split()

print(str(type(terms)))

for item in terms:
    if item[0] == "#":
        print(item)

<class 'list'>
#antiTrump
#tweet

In [120]:
# Group tweets by user and show account info

user = df.groupby('userID')

PROFILE_COLS = [
    "followers_account",
    "friends_count",
    "location"
]

users = user[PROFILE_COLS].max()

<class 'pandas.core.frame.DataFrame'>

        followers_account  friends_count                     location
userID
6                    4739           1822                  Trenton, NJ
9                    2491           2653              Birmingham, AL.
11                     26             70                 Alabama, USA
27                   1704           2015                    Centre,AL
51                    595            251               Birmingham, AL
52                    214            777                       Alaska
53                    274            176                       Alaska
62                    225            450                  mobile, al.
73                    605            891                    Anchorage
74                    146            443               Alabaster, AL
78                    145            390                       Alaska
99                    973            608                 Fayetteville
113                   913            862                  Gilbert, AZ
114                   583           1997                   Hoover, AL
138                   251            288             Jacksonville, AL
149                   114            206           Northwest Arkansas
156                    61            223                     Arizona
161                   203            127                  Little Rock
167                   158            361             Searcy, Arkansas
180                   615           1450                      Arizona
193                   139            457                    Tempe, AZ
196                  1944           1900             Phoenix, Arizona
203                    67             19           Birmingham Alabama
207                   123            301                 Maumelle, AR
216                   745            233                   Gilbert AZ
226                   236            632                  Phoenix, AZ
236                   916            495                    S0-Hi, AZ
239                   638            421             Phoenix, Arizona
240                 64749           1019                      Arizona
244                   126            205                  Phoenix, AZ
...                   ...            ...                          ...
22679                 129            112                Lancaster, PA
22681                 531            221                     York, PA
22684                  49            208          Zionsville, Indiana
22686                 202            391                   Storrs, CT
22695                 180            161                New York City
22701                 300            195                          NYC
22707                 420            394                          NaN
22711                 631            939                New York City
22712                  80            691                        pluto
22718                  61            123                          NaN
22721                 342            149                new york city
22724                2832            831                 brooklyn, ny
22728                 186            591                          NaN
22729                 402            754     Boca Raton - Tallahassee
22737                 145            187                  Phoenix, AZ
22753                 133            196           Baltimore Maryland
22756                1150            437                   Louisiana
22761                 326            419                Lafayette, LA
22763                 619            596                Da Parish, LA
22778                  78            254                    Tulsa, OK
22787                 775           2193                   Monticello
22792                 526            486     New Britain, Connecticut
22793                1607            989                   Boston, MA
22796                2140            683                 Lawrence, KS
22820                  38             82                     Reno, NV
22823                1722           1164          Ann Arbor, Michigan
22826                 453            350  Shelby Twp ▶️ East Lansing
22829                1674           1435                     Michigan
22850                 426            198           Cedar Rapids, Iowa
22853                 426             92                  Lincoln, NE

[3137 rows x 3 columns]